/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

group = "com.cryptek"
version = "1.0.0-SNAPSHOT"
description = "playground"
//java.sourceCompatibility = JavaVersion.VERSION_23
//java.targetCompatibility = JavaVersion.VERSION_23

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    options.compilerArgs.add("--enable-preview")
    options.compilerArgs.add("-Xlint:preview")
    options.release.set(23)
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.withType<JavaExec>() {
    jvmArgs("--enable-preview")
}

tasks.withType<Test>() {
    jvmArgs("--enable-preview")
    useJUnitPlatform()
}
